TravelWeb/Controllers/ManagerhtController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TravelWeb.EF;
using TravelWeb.Models;
using TravelWeb.Models.DTO;

namespace TravelWeb.Controllers
{
    public class ManagerhtController : Controller
    {
        private readonly HotelContext context;

        


        // open db context 
        public ManagerhtController()
        {
            context = new HotelContext();
           
        }

        // GET: Managerht
        public ActionResult Index()
        {
            return View();
        }


        //////////////////////////////
        [Authorize(Roles = SecurityRoles.Manager)]
        [HttpGet]
        public ActionResult CreateTypeRoom()
        {
            ViewBag.Hotel = getListHt();
            return View();
        }

        [HttpPost]
        public ActionResult CreateTypeRoom(TypeRoom a)
        {

            CustomValidationLocation(a);
            if (!ModelState.IsValid)
            {

                ViewBag.Hotel = getListHt();
                return View(a); // return lai Create.cshtml

            }
            else
            {

               
                    if (a.Description == null)
                    {
                        a.Description = "No Description!";
                    }

                    context.TypeRooms.Add(a);
                    context.SaveChanges();
                

                //TempData["message"] = $"Successfully add Location {a.Name} to system!";

                return RedirectToAction("Index");
            }



        }

        private void CustomValidationLocation(TypeRoom a)
        {

            if (string.IsNullOrEmpty(a.Image))
            {
                ModelState.AddModelError("Image", "Please input ImageUrl");
            }


        }
        [Authorize(Roles = SecurityRoles.Manager)]
        [HttpGet]
        public ActionResult EditTypeRoom(int id)
        {
            ViewBag.Hotel = getListHt();
            // lay category qua id tu db
           
                var Location = context.TypeRooms.FirstOrDefault(c => c.Id == id);
                return View(Location);
            
        }

        [HttpPost]
        public ActionResult EditTypeRoom(int id, TypeRoom a)
        {
            CustomValidationLocation(a);
            if (!ModelState.IsValid)
            {
                ViewBag.Hotel = getListHt();
                return View(a); 
            }
            else
            {
               
                    context.Entry<TypeRoom>(a).State = System.Data.Entity.EntityState.Modified;

                    context.SaveChanges();
                

                return RedirectToAction("Index");
            }

        }
        [Authorize(Roles = SecurityRoles.Manager)]
        public ActionResult ShowTypeRoom()
        {

            var Type = (from ty in context.TypeRooms
                        join ht in context.Hotels on ty.HotelId equals ht.Id into hoteltype
                        from ht in hoteltype.DefaultIfEmpty()
                        select new TypeRoomDTO
                        {
                            TypeId = ty.Id,
                            NameType = ty.Name,
                            Image = ty.Image,
                            Price = ty.Price,
                            MaxNumberRoom = context.Rooms.Where(x => x.TypeId == ty.Id).Count(),
                            Description = ty.Description,
                            HotelName = ht.Name,
                            AvailableRoom = ty.AvailableRoom != null ? ty.AvailableRoom : context.Rooms.Where(x => x.TypeId == ty.Id && x.Status.Equals("available")).Count(),
                        }).AsEnumerable();

            // var Type = Db.TypeRooms.OrderBy(a => a.Id).ToList();
            return View(Type);

        }








        [Authorize(Roles = SecurityRoles.Manager)]
        public ActionResult ShowWating()
        {
            var request = (from bk in context.Bookings
                           join ty in context.TypeRooms on bk.TypeRoomId equals ty.Id
                           join ht in context.Hotels on ty.HotelId equals ht.Id
                           select
                                new BookingTypeHtDTO
                                {
                                    Id = bk.Id,
                                    CustomerName = bk.CustomerName,
                                    CustomerAdress = bk.CustomerAdress,
                                    CustomerPhone = bk.CustomerPhone,
                                    BookingFrom = bk.BookingFrom,
                                    BookingTo = bk.BookingTo,
                                    NumberOfMember = bk.NumberOfMember,
                                    NumberRoomBook = bk.NumberRoomBook,
                                    Types = ty.Name,
                                    Statuses = bk.Status,
                                    HotelName = ht.Name,
                                    Price = ty.Price,


                                }
                          ).ToList().Where(p => p.Statuses == "wating");



            //var request = (from re in context.Bookings
            //              where re.status == "wating"
            //              select re).ToList();
            return View(request);


        }


        public ActionResult ManagerRoomBooking()
        {
            var bookingroom = (from br in context.BookingRooms
                           join ro in context.Rooms on br.RoomId equals ro.Id
                           join bk in context.Bookings on br.BookingId equals bk.Id
                           join ty in context.TypeRooms on  ro.TypeId equals ty.Id
                           join ht in context.Hotels on ty.HotelId equals ht.Id
                           select
                                new BookingRoomDTO
                                {
                                    Id = br.Id,
                                    CustomerName = bk.CustomerName,
                                    CustomerAdress = bk.CustomerAdress,
                                    RoomNo = ro.RoomNo,
                                    Type = ty.Name
                                   


                                }
                          ).ToList();



            return View(bookingroom);


        }





        [Authorize(Roles = SecurityRoles.Manager)]
        public ActionResult ShowActive()
        {
            var request = (from bk in context.Bookings
                           join ty in context.TypeRooms on bk.TypeRoomId equals ty.Id
                           join ht in context.Hotels on ty.HotelId equals ht.Id
                           select
                            new BookingTypeHtDTO
                            {
                                Id = bk.Id,
                                CustomerName = bk.CustomerName,
                                CustomerAdress = bk.CustomerAdress,
                                CustomerPhone = bk.CustomerPhone,
                                BookingFrom = bk.BookingFrom,
                                BookingTo = bk.BookingTo,
                                NumberOfMember = bk.NumberOfMember,
                                NumberRoomBook = bk.NumberRoomBook,
                                Types = ty.Name,
                                Statuses = bk.Status,
                                HotelName = ht.Name,
                                Price = ty.Price,


                            }
                         ).ToList().Where(p => p.Statuses == "active");
            return View(request);
        }

        [Authorize(Roles = SecurityRoles.Manager)]
        public ActionResult ShowHistory()
        {
            var request = (from bk in context.Bookings
                           join ty in context.TypeRooms on bk.TypeRoomId equals ty.Id
                           join ht in context.Hotels on ty.HotelId equals ht.Id
                           select
                            new BookingTypeHtDTO
                            {
                                Id = bk.Id,
                                CustomerName = bk.CustomerName,
                                CustomerAdress = bk.CustomerAdress,
                                CustomerPhone = bk.CustomerPhone,
                                BookingFrom = bk.BookingFrom,
                                BookingTo = bk.BookingTo,
                                NumberOfMember = bk.NumberOfMember,
                                NumberRoomBook = bk.NumberRoomBook,
                                Types = ty.Name,
                                Statuses = bk.Status,
                                HotelName = ht.Name,
                                Price = ty.Price,


                            }
                         ).ToList().Where(p => p.Statuses == "history");
            return View(request);
        }


        public ActionResult ShowLate()
        {
            var request = (from bk in context.Bookings
                           join ty in context.TypeRooms on bk.TypeRoomId equals ty.Id
                           join ht in context.Hotels on ty.HotelId equals ht.Id
                           select
                            new BookingTypeHtDTO
                            {
                                Id = bk.Id,
                                CustomerName = bk.CustomerName,
                                CustomerAdress = bk.CustomerAdress,
                                CustomerPhone = bk.CustomerPhone,
                                BookingFrom = bk.BookingFrom,
                                BookingTo = bk.BookingTo,
                                NumberOfMember = bk.NumberOfMember,
                                NumberRoomBook = bk.NumberRoomBook,

TravelWeb/Views/Managerht/Confirm.cshtml
@model TravelWeb.Models.Booking
@{
    ViewBag.Title = "Confirm";
    Layout = "~/Views/Managerht/_LayoutManager.cshtml";
    List<TravelWeb.Models.Room> availableRoom = ViewBag.AvailableRooms;
}

<h2>Confirm</h2>



<div>


    @if (!ViewData.ModelState.IsValid)
    {
        @Html.ValidationSummary(false, "Error Summary", new { @class = "text-danger" })
    }
    <div class="container">

        <select id="select-room" class="form-control" multiple>
            @foreach (var room in availableRoom)
            {
                <option value="@room.Id">@room.RoomNo</option>
            }
        </select>


        <br />
        @*<button type="submit" id="btn-submit" btn class="btn btn-dark">Submit</button>*@
        <a id="btn-submit" class="btn btn-primary btn-lg" href=@Url.Action("ShowWating","Managerht")>Submit</a>

    </div>
</div>

<script>
    $(document).ready(function () {
        var arr = [];
        $('#select-room').change(function (e) {
            console.log($('#select-room').val())
            arr = $('#select-room').val()
        })
        $('#btn-submit').click(function () {
            LoadData(arr);
        })
        function LoadData(arr) {
            jQuery.ajax({
                type: "POST",
                url: "@Url.Action("AddRoom","Managerht")",
                data: { Array: arr, BookingId: @ViewBag.BookingId },
            dataType: "array",
            success: function (msg) {
                console.log(msg)
            },
        })
        }
    })
</script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.6.1.min.js"
        integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

TravelWeb/Views/Managerht/CreateRoom.cshtml
@model TravelWeb.Models.Room
@{
    ViewBag.Title = "CreateRoom";
    Layout = "~/Views/Managerht/_LayoutManager.cshtml";
}

<h2>CreateRoom</h2>
<div class="container">
    <h1 class="display-4">New Room</h1>

    @if (!ViewData.ModelState.IsValid)
    {
        @Html.ValidationSummary(false, "Error Summary", new { @class = "text-danger" })
    }

    @using (Html.BeginForm(FormMethod.Post))
    {

        <div class="form-group">
            @Html.LabelFor(m => m.TypeId, htmlAttributes: new { @class = "form-weight-bold" })
            @Html.DropDownListFor(m => m.TypeId, (IEnumerable<SelectListItem>)ViewBag.Type, htmlAttributes
           : new { @class = "form-control" }
           )
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.RoomNo,
              htmlAttributes: new { @class = "font-weight-bold" })


            @Html.EditorFor(m => m.RoomNo,
             new
             {
               htmlAttributes = new { @class = "form-control" }
             })
        </div>
       


        <br />

        <button type="submit" class="btn btn-dark">Submit</button>
    }

</div>

TravelWeb/Views/Managerht/CreateTypeRoom.cshtml
@model TravelWeb.Models.TypeRoom
@{
    ViewBag.Title = "CreateTypeRoom";
    Layout = "~/Views/Managerht/_LayoutManager.cshtml";
}

<h2>CreateTypeRoom</h2>
<div class="container">
    <h1 class="display-4">New Type Room</h1>

    @if (!ViewData.ModelState.IsValid)
    {
        @Html.ValidationSummary(false, "Error Summary", new { @class = "text-danger" })
    }

    @using (Html.BeginForm(FormMethod.Post))
    {
        
        <div class="form-group">
            @Html.LabelFor(m => m.HotelId, htmlAttributes: new { @class = "form-weight-bold" })
            @Html.DropDownListFor(m => m.HotelId, (IEnumerable<SelectListItem>)ViewBag.Hotel, htmlAttributes
           : new { @class = "form-control" }
           )
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Name,
              htmlAttributes: new { @class = "font-weight-bold" })


            @Html.EditorFor(m => m.Name,
             new
             {
               htmlAttributes = new { @class = "form-control" }
             })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Image,
              htmlAttributes: new { @class = "font-weight-bold" })


            @Html.EditorFor(m => m.Image,
             new
             {
               htmlAttributes = new { @class = "form-control" }
             })
        </div>
        
        <div class="form-group">
            @Html.LabelFor(m => m.Price,
              htmlAttributes: new { @class = "font-weight-bold" })


            @Html.EditorFor(m => m.Price,
             new
             {
               htmlAttributes = new { @class = "form-control" }
             })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Description, new { @class = "font-weight-bold" })
            @Html.EditorFor(m => m.Description,
            new
            {
              htmlAttributes = new { @class = "form-control" }
            })
        </div>
        <br />

        <button type="submit" class="btn btn-dark">Submit</button>
    }

</div>

TravelWeb/Views/Managerht/DeleteTypeRoom.cshtml
@model TravelWeb.Models.TypeRoom
@{
    ViewBag.Title = "DeleteTypeRoom";
    Layout = "~/Views/Managerht/_LayoutManager.cshtml";
   
}

<h2>DeleteTypeRoom</h2>
<div class="container">
    @using (Html.BeginForm(FormMethod.Post))
    {
        @Html.HiddenFor(m => m.Id)
        <div class="form-group">
            @Html.LabelFor(m => m.Name,
              htmlAttributes: new { @class = "font-weight-bold" })


            @Html.EditorFor(m => m.Name,
             new
             {
               htmlAttributes = new { @class = "form-control" }
             })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Description, new { @class = "font-weight-bold" })
            @Html.EditorFor(m => m.Description,
            new
            {
              htmlAttributes = new { @class = "form-control" }
            })
        </div>
        <br />

        <button type="submit" class="btn btn-dark">Submit</button>
    }

</div>

TravelWeb/Views/Managerht/EditTypeRoom.cshtml
@model TravelWeb.Models.TypeRoom

@{
    ViewBag.Title = "EditTypeRoom";
    Layout = "~/Views/Managerht/_LayoutManager.cshtml";
}

<h2>EditTypeRoom</h2>

<div class="container">
    <h1 class="display-4">Edit Type Room</h1>

    @if (!ViewData.ModelState.IsValid)
    {
        @Html.ValidationSummary(false, "Error Summary", new { @class = "text-danger" })
    }

    @using (Html.BeginForm(FormMethod.Post))
    {

        <div class="form-group">
            @Html.LabelFor(m => m.HotelId, htmlAttributes: new { @class = "form-weight-bold" })
            @Html.DropDownListFor(m => m.HotelId, (IEnumerable<SelectListItem>)ViewBag.Hotel, htmlAttributes
           : new { @class = "form-control" }
           )
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Name,
              htmlAttributes: new { @class = "font-weight-bold" })


            @Html.EditorFor(m => m.Name,
             new
             {
               htmlAttributes = new { @class = "form-control" }
             })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Image,
              htmlAttributes: new { @class = "font-weight-bold" })


            @Html.EditorFor(m => m.Image,
             new
             {
               htmlAttributes = new { @class = "form-control" }
             })
        </div>
        @*<div class="form-group">
            @Html.LabelFor(m => m.MaxNumberRoom,
              htmlAttributes: new { @class = "font-weight-bold" })


            @Html.EditorFor(m => m.MaxNumberRoom,
             new
             {
               htmlAttributes = new { @class = "form-control" }
             })
        </div>*@
        <div class="form-group">
            @Html.LabelFor(m => m.Price,
              htmlAttributes: new { @class = "font-weight-bold" })


            @Html.EditorFor(m => m.Price,
             new
             {
               htmlAttributes = new { @class = "form-control" }
             })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Description, new { @class = "font-weight-bold" })
            @Html.EditorFor(m => m.Description,
            new
            {
              htmlAttributes = new { @class = "form-control" }
            })
        </div>
        <br />

        <button type="submit" class="btn btn-dark">Submit</button>
    }

</div>

TravelWeb/Views/Managerht/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Managerht/_LayoutManager.cshtml";

}

@if (TempData["message"] != null)
{
    <script>
        alert('@Html.Raw(TempData["message"])')
    </script>
}



<div class="row gx-4 gx-lg-5 align-items-center my-5">
    <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://v-biz.vn/static/media/Travel.ff88c854.jpg" alt="..." /></div>
    <div class="col-lg-5">
        <h1 class="font-weight-light">Booking Hotel</h1>
        <p>Take you where you want to go. Let's explore together</p>
        <a class="btn btn-primary btn-lg" href=@Url.Action("ShowTypeRoom","Managerht")>Manager Type Room</a>
    </div>
</div>

TravelWeb/Views/Managerht/ManagerRoomBooking.cshtml
@model IEnumerable<TravelWeb.Models.DTO.BookingRoomDTO>
@{
    ViewBag.Title = "ManagerRoomBooking";
    Layout = "~/Views/Managerht/_LayoutManager.cshtml";
}

<h2>Room Assign</h2>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

<div>

    <input id="myInput" type="text" placeholder="Search..">
    <br><br>
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>

                <th scope="col">@Html.DisplayNameFor(model => model.CustomerName)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.CustomerAdress)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.RoomNo)</th>

                <th scope="col">@Html.DisplayNameFor(model => model.Type)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.HotelName)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.Status)</th>


                <th scope="col">&nbsp;</th>
                <th scope="col">&nbsp;</th>
            </tr>
        </thead>
        <tbody id="myTable">
            @foreach (var c in Model)
            {
            <tr class="Search">

                <td>@Html.DisplayFor(model => c.CustomerName)</td>
                <td>@Html.DisplayFor(model => c.CustomerAdress)</td>
                <td>@Html.DisplayFor(model => c.RoomNo)</td>
                <td>@Html.DisplayFor(model => c.HotelName)</td>
                <td>@Html.DisplayFor(model => c.Type)</td>
                <td>@Html.DisplayFor(model => c.Status)</td>




            </tr>
            }
        </tbody>
    </table>


</div>

TravelWeb/Views/Managerht/_LayoutManager.cshtml
<!--<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"
            integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a href="#"><img src="https://tse1.mm.bing.net/th?id=OIP.muh0ekDqWCE8tVXccpZrKwHaF7&pid=Api&P=0" alt="HTML tutorial" style="width:65px;height:65px;"></a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("ShowTypeRoom", "Managerht")">Home <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        TypeRoom
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="@Url.Action("CreateTypeRoom", "Managerht")">New Type</a>
                        <a class="dropdown-item" href="@Url.Action("ShowTypeRoom", "Managerht")"> Manager Type</a>
                        <div class="dropdown-divider"></div>

                    </div>
                </li>-->

                @*<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Room
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("CreateRoom", "Managerht")">New Room</a>
                            <a class="dropdown-item" href="@Url.Action("ShowRoom", "Managerht")"> Manager Room</a>
                            <div class="dropdown-divider"></div>

                        </div>
                    </li>*@

                <!--<li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("ShowWating", "Managerht")">Wating checkin <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("ShowActive", "Managerht")">Active Booking <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("ShowHistory", "Managerht")">Booked <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("ShowLate", "Managerht")">Late <span class="sr-only">(current)</span></a>
                </li>


            </ul>



            <a class="btn btn-danger float-right" href="@Url.Action("Logout", "Login")" role="button">Logout</a>
        </div>
    </nav>

    <div>

    </div>
</body>
</html>-->



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Booking Hotel </title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->

    <link href="~/Theme3/css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-5">
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Managerht")">Home</a></li>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    
                   
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("CreateTypeRoom", "Managerht")"">Create RoomType</a></li>
                   
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("ShowWating", "Managerht")">Waiting check-in</a></li>
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("ShowActive", "Managerht")">Active Booking</a></li>
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("ShowHistory", "Managerht")">Booked</a></li>
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("ShowLate", "Managerht")">Late Check-in</a></li>
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("ManagerRoomBooking", "Managerht")">Room Assign</a></li>
                    <a class="btn btn-danger float-right" href="@Url.Action("Logout", "Login")" role="button">Logout</a>

                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Content-->
    <div class="container px-4 px-lg-5">
        <!-- Heading Row-->
        <!-- Call to Action-->
        <!-- Content Row-->
        <div class="row gx-4 gx-lg-5">

            @RenderBody()


        </div>
    </div>
    <!-- Footer-->
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->

    <script src="~/Theme3/js/scripts.js"></script>
</body>
</html>